services:
    backend:
        build: Backend
        env_file:
            - path: .env
        volumes:
            - templates:/timesy/templates
        command: /bin/bash -c "mvn spring-boot:run"
        network_mode: host
        restart: unless-stopped
    frontend:
        build: Frontend
        command: /bin/bash -c "ng serve"
        network_mode: host
        restart: unless-stopped
        depends_on:
            backend:
                condition: service_started
                restart: true

volumes:
    templates:
        external: true
        name: ${TEMPLATE_FOLDER}
